### PR TITLE
Update SnappedPoint.yml

### PR DESCRIPTION
**Pull request by nora-soderlund**
Clarifying that the Nearest Roads API may send several objects for the same index. This differs from the Snap to Roads API but isn't outlined here:
https://developers.google.com/maps/documentation/roads/nearest

See nearest roads vs snap to roads:
https://roads.googleapis.com/v1/nearestRoads?points=58.3441718,12.3007768&key=REDACTED https://roads.googleapis.com/v1/snapToRoads?path=58.3441718,12.3007768&key=REDACTED

### CODE REVIEW

**Comment by nora-soderlund** [comment]
Actually, it might be a better idea to change this text to plural?

The Roads API takes up to 100 independent coordinates, and returns the closest road segment for each point. The points passed do not need to be part of a continuous path.

**Review by amuramoto — APPROVED** [review]

**Comment by wangela** [comment]
@nora-soderlund thank you for your contribution. We have updated our workflow to update dist after the pull request is merged. I apologize for using update-dist to add changed files to your pull request which are causing merge conflicts. Would you please:

1. Revert the changes to /dist by `git checkout origin/main -- dist`
2. Commit the reverted changes

If all goes correctly, there should only be 3 changed files left in the PR; the ones under /specification.

Thank you!

**Comment by nora-soderlund** [comment]
@wangela I've reverted the changes to /dist now, I wasn't sure how to do it earlier, thank you! :)

**Comment by nora-soderlund** [comment]
@wangela

**Comment by amuramoto** [comment]
Thanks for the PR @nora-soderlund!

**Pull request merged**
