### PR TITLE
Typo Corrected

### PR DESCRIPTION
**Pull request by ShubhamDalal**
Earlier : continaing
Now: containing

Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by ShubhamDalal** [comment]
@googlebot I signed it!

**Comment by jpoehnelt** [comment]
Had to take a workaround to getting this merged. https://github.com/googlemaps/openapi-specification/commit/5242cdd53ca51c9d7aebe1f5dc05e70c04588d7d Thanks for the fix.

**Pull request closed without merging**
