### PR TITLE
fix: typo in place review

### PR DESCRIPTION
**Pull request by zulu-caPWN**
original: this field may by empty
new: this field may be empty

Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by zulu-caPWN** [comment]
@googlebot I signed it!

**Comment by zulu-caPWN** [comment]
ready for review

**Comment by jpoehnelt** [comment]
Thanks!

**Comment by zulu-caPWN** [comment]
My first PR ever.

Thank You!

**Comment by jpoehnelt** [comment]
Thank you!

@zulu-caPWN, Do you mind answering a couple questions?

####  Where did you find this typo? 
1. OpenAPI Spec
1. Documentation at https://developers.google.com/maps/... 
1. Postman Collection
1. Other

####  Are you generating client or server libraries from the OpenAPI spec? 
(Y/N)

**Comment by zulu-caPWN** [comment]
I believe that it was #2

**Pull request merged**
